services:
  aneurism-iv:
    build: .
    ports:
      - "7777:7777"
      - "7778:7778"
      - "7779:7779"
    tty: true
    stdin_open: true
    container_name: aniv-ds
    user: "1000:1000"
    volumes:
      - "./ds:/home/steam/aniv-ds/"
      - "./config:/home/steam/.config/unity3d/Vellocet/ANEURISM IV"
    